import type { Definition } from './definitions';

/**
 * Conventional terms and abbreviations.
 *
 * GENERATED by scripts/gen-abbreviations.mjs from
 * fixtures/definitions/abbreviations.json. Do not edit by hand — re-run the
 * generator.
 *
 * These are the one part of a prospectus glossary safe to carry across issuers
 * wholesale: an expansion contains no issuer facts by construction. The
 * definitions proper had to be authored individually (D21) because issuer
 * specifics hid inside them as bare numbers and registration codes. The
 * generator still checks, and refuses to emit if it finds any.
 *
 * Source: Om Galaxy RHP pp.18-24, 129 entries.
 */
export const ABBREVIATIONS: Definition[] = [
  {
    term: 'A/c',
    kind: 'standard',
    describe: () => 'Account',
  },
  {
    term: 'AAEC',
    kind: 'standard',
    describe: () => 'Appreciable adverse effect on competition',
  },
  {
    term: 'AGM',
    kind: 'standard',
    describe: () => 'Annual General Meeting',
  },
  {
    term: 'AIF',
    kind: 'standard',
    describe: () => 'Alternative Investment Funds registered under the Securities and Exchange Board of India (Alternative Investment Funds) Regulations, 2012, as amended',
  },
  {
    term: 'Amt.',
    kind: 'standard',
    describe: () => 'Amount',
  },
  {
    term: 'AOA',
    kind: 'standard',
    describe: () => 'Articles of Association',
  },
  {
    term: 'Approx',
    kind: 'standard',
    describe: () => 'Approximately',
  },
  {
    term: 'AS / Accounting Standard',
    kind: 'standard',
    describe: () => 'Accounting Standards as issued by the Institute of Chartered Accountants of India',
  },
  {
    term: 'ASBA',
    kind: 'standard',
    describe: () => 'Applications Supported by Blocked Amount',
  },
  {
    term: 'AY',
    kind: 'standard',
    describe: () => 'Assessment Year',
  },
  {
    term: 'BG/LC',
    kind: 'standard',
    describe: () => 'Bank Guarantee / Letter of Credit',
  },
  {
    term: 'BIFR',
    kind: 'standard',
    describe: () => 'Board for Industrial and Financial Reconstruction',
  },
  {
    term: 'Bn',
    kind: 'standard',
    describe: () => 'Billion',
  },
  {
    term: 'BNSS',
    kind: 'standard',
    describe: () => 'Bhartiya Nagrik Suraksha Sanhita, 2023',
  },
  {
    term: 'BRLM',
    kind: 'standard',
    describe: () => 'Book Running Lead Manager',
  },
  {
    term: 'C.P.C.',
    kind: 'standard',
    describe: () => 'Code of Civil Procedure, 1908',
  },
  {
    term: 'CA',
    kind: 'standard',
    describe: () => 'Chartered Accountant',
  },
  {
    term: 'CAN',
    kind: 'standard',
    describe: () => 'Confirmation of Allocation Note',
  },
  {
    term: 'CC',
    kind: 'standard',
    describe: () => 'Cash Credit',
  },
  {
    term: 'CCI',
    kind: 'standard',
    describe: () => 'Competition Commission of India',
  },
  {
    term: 'CDSL',
    kind: 'standard',
    describe: () => 'Central Depository Services (India) Limited',
  },
  {
    term: 'CENVAT',
    kind: 'standard',
    describe: () => 'Central Value Added Tax',
  },
  {
    term: 'CFO',
    kind: 'standard',
    describe: () => 'Chief Financial Officer',
  },
  {
    term: 'CIN',
    kind: 'standard',
    describe: () => 'Corporate Identity Number',
  },
  {
    term: 'Circular',
    kind: 'standard',
    describe: () => 'CFD-POD2/I/4518/2026 dated February 9, 2026',
  },
  {
    term: 'Client ID',
    kind: 'standard',
    describe: () => 'Client identification number of the Bidder\'s beneficiary account',
  },
  {
    term: 'CMD',
    kind: 'standard',
    describe: () => 'Chairman and Managing Director',
  },
  {
    term: 'Companies Act, 1956',
    kind: 'standard',
    describe: () => 'Companies Act, 1956 (without reference to the provisions that have ceased upon notification of the Companies Act, 2013) along with the relevant rules made thereunder',
  },
  {
    term: 'Companies Act, 2013',
    kind: 'standard',
    describe: () => 'Companies Act, 2013 to the extent in force pursuant to the notification of sections of the Companies Act, 2013 along with the relevant rules made thereunder as amended',
  },
  {
    term: 'CS',
    kind: 'standard',
    describe: () => 'Company Secretary',
  },
  {
    term: 'CSR',
    kind: 'standard',
    describe: () => 'Corporate Social Responsibility',
  },
  {
    term: 'CST',
    kind: 'standard',
    describe: () => 'Central Sales Tax',
  },
  {
    term: 'CWA/ICWA',
    kind: 'standard',
    describe: () => 'Cost and Works Accountant',
  },
  {
    term: 'Depositories Act',
    kind: 'standard',
    describe: () => 'The Depositories Act, 1996, read with the rules, regulations, clarifications and modifications thereunder',
  },
  {
    term: 'Depository',
    kind: 'standard',
    describe: () => 'A depository registered with the SEBI under the Securities and Exchange Board of India (Depositories and Participants) Regulations, 2018',
  },
  {
    term: 'DIN',
    kind: 'standard',
    describe: () => 'Director Identification Number',
  },
  {
    term: 'DP',
    kind: 'standard',
    describe: () => 'Depository Participant',
  },
  {
    term: 'DP ID',
    kind: 'standard',
    describe: () => 'Depository Participant\'s Identification Number',
  },
  {
    term: 'EBITDA',
    kind: 'standard',
    describe: () => 'Earnings Before Interest, Taxes, Depreciation & Amortization',
  },
  {
    term: 'EGM /EOGM',
    kind: 'standard',
    describe: () => 'Extraordinary General Meeting',
  },
  {
    term: 'EXIM/ EXIM Policy',
    kind: 'standard',
    describe: () => 'Export – Import Policy',
  },
  {
    term: 'FCNR Account',
    kind: 'standard',
    describe: () => 'Foreign Currency Non-Resident (Bank) account established in accordance with the provisions of FEMA',
  },
  {
    term: 'FDI',
    kind: 'standard',
    describe: () => 'Foreign Direct Investment',
  },
  {
    term: 'FEMA',
    kind: 'standard',
    describe: () => 'Foreign Exchange Management Act, 1999 as amended from time to time, and the regulations framed there under.',
  },
  {
    term: 'FEMA Rules',
    kind: 'standard',
    describe: () => 'Foreign Exchange Management (Non-debt Instruments) Rules, 2019',
  },
  {
    term: 'FIIs',
    kind: 'standard',
    describe: () => 'Foreign Institutional Investors (as defined under Foreign Exchange Management (Transfer or Issue of Security by a Person Resident outside India) Regulations, 2000) registered with SEBI under applicable laws in India',
  },
  {
    term: 'FIs',
    kind: 'standard',
    describe: () => 'Financial Institutions',
  },
  {
    term: 'FTA',
    kind: 'standard',
    describe: () => 'Foreign Trade (Development and Regulation) Act, 1992',
  },
  {
    term: 'FV',
    kind: 'standard',
    describe: () => 'Face Value',
  },
  {
    term: 'FY / Fiscal/Financial Year',
    kind: 'standard',
    describe: () => 'Period of twelve months ended March 31 of that particular year, unless otherwise stated',
  },
  {
    term: 'GDP',
    kind: 'standard',
    describe: () => 'Gross Domestic Product',
  },
  {
    term: 'GIR Number',
    kind: 'standard',
    describe: () => 'General Index Registry Number',
  },
  {
    term: 'GoI/Government',
    kind: 'standard',
    describe: () => 'Government of India',
  },
  {
    term: 'GST',
    kind: 'standard',
    describe: () => 'Goods and Services Tax',
  },
  {
    term: 'GVA',
    kind: 'standard',
    describe: () => 'Gross Value Added',
  },
  {
    term: 'I.T. Act',
    kind: 'standard',
    describe: () => 'Income Tax Act, 1961, as amended from time to time',
  },
  {
    term: 'IBC',
    kind: 'standard',
    describe: () => 'The Insolvency and Bankruptcy Code, 2016',
  },
  {
    term: 'ICAI',
    kind: 'standard',
    describe: () => 'The Institute of Chartered Accountants of India',
  },
  {
    term: 'ICSI',
    kind: 'standard',
    describe: () => 'The Institute of Company Secretaries of India',
  },
  {
    term: 'ICWAI',
    kind: 'standard',
    describe: () => 'The Institute of Cost Accountants of India',
  },
  {
    term: 'IFRS',
    kind: 'standard',
    describe: () => 'International Financial Reporting Standards',
  },
  {
    term: 'INR / / Rupees',
    kind: 'standard',
    describe: () => 'Indian Rupees, the legal currency of the Republic of India',
  },
  {
    term: 'IPO',
    kind: 'standard',
    describe: () => 'Initial Public Offer',
  },
  {
    term: 'IRDA',
    kind: 'standard',
    describe: () => 'Insurance Regulatory and Development Authority',
  },
  {
    term: 'ISIN',
    kind: 'standard',
    describe: () => 'International Securities Identification Number',
  },
  {
    term: 'IST',
    kind: 'standard',
    describe: () => 'Indian Standard Time',
  },
  {
    term: 'IT Act',
    kind: 'standard',
    describe: () => 'The Information Technology Act, 2000',
  },
  {
    term: 'IT Authorities',
    kind: 'standard',
    describe: () => 'Income Tax Authorities',
  },
  {
    term: 'IT Rules',
    kind: 'standard',
    describe: () => 'Income Tax Rules, 1962, as amended, except as stated otherwise',
  },
  {
    term: 'JV/ Joint Venture',
    kind: 'standard',
    describe: () => 'A commercial enterprise undertaken jointly by two or more parties which otherwise retain their distinct identities',
  },
  {
    term: 'KMP',
    kind: 'standard',
    describe: () => 'Key Managerial Personnel',
  },
  {
    term: 'KPI',
    kind: 'standard',
    describe: () => 'Explanation',
  },
  {
    term: 'LLP',
    kind: 'standard',
    describe: () => 'Limited Liability Partnership',
  },
  {
    term: 'Ltd.',
    kind: 'standard',
    describe: () => 'Limited',
  },
  {
    term: 'Merchant Banker',
    kind: 'standard',
    describe: () => 'Merchant Banker as defined under the Securities and Exchange Board of India (Merchant Bankers) Regulations, 1992',
  },
  {
    term: 'Mn',
    kind: 'standard',
    describe: () => 'Million',
  },
  {
    term: 'MoU',
    kind: 'standard',
    describe: () => 'Memorandum of Understanding',
  },
  {
    term: 'MSMED Act',
    kind: 'standard',
    describe: () => 'Micro, Small and Medium Enterprises Development Act, 2006',
  },
  {
    term: 'NA',
    kind: 'standard',
    describe: () => 'Not Applicable',
  },
  {
    term: 'NACH',
    kind: 'standard',
    describe: () => 'National Automated Clearing House',
  },
  {
    term: 'NAV',
    kind: 'standard',
    describe: () => 'Net Asset Value',
  },
  {
    term: 'NCLT',
    kind: 'standard',
    describe: () => 'National Company Law Tribunal',
  },
  {
    term: 'NECS',
    kind: 'standard',
    describe: () => 'National Electronic Clearing System',
  },
  {
    term: 'NEFT',
    kind: 'standard',
    describe: () => 'National Electronic Funds Transfer',
  },
  {
    term: 'NOC',
    kind: 'standard',
    describe: () => 'No Objection Certificate',
  },
  {
    term: 'NPV',
    kind: 'standard',
    describe: () => 'Net Present Value',
  },
  {
    term: 'NRIs',
    kind: 'standard',
    describe: () => 'Non-Resident Indians',
  },
  {
    term: 'NSDL',
    kind: 'standard',
    describe: () => 'National Securities Depository Limited',
  },
  {
    term: 'NSE',
    kind: 'standard',
    describe: () => 'National Stock Exchange of India Limited',
  },
  {
    term: 'P.A.',
    kind: 'standard',
    describe: () => 'Per Annum',
  },
  {
    term: 'P/E Ratio',
    kind: 'standard',
    describe: () => 'Price/Earnings Ratio',
  },
  {
    term: 'PAN',
    kind: 'standard',
    describe: () => 'Permanent Account Number',
  },
  {
    term: 'PAT',
    kind: 'standard',
    describe: () => 'Profit After Tax',
  },
  {
    term: 'PBT',
    kind: 'standard',
    describe: () => 'Profit Before Tax',
  },
  {
    term: 'PF',
    kind: 'standard',
    describe: () => 'Provident Fund',
  },
  {
    term: 'POA',
    kind: 'standard',
    describe: () => 'Power of Attorney',
  },
  {
    term: 'Profit After Tax ("PAT")',
    kind: 'standard',
    describe: () => 'Restated profit for the year represents the profit that our Company makes for the financial year. It provides information regarding the profitability of the business of our Company',
  },
  {
    term: 'PSU',
    kind: 'standard',
    describe: () => 'Public Sector Undertaking(s)',
  },
  {
    term: 'Pvt.',
    kind: 'standard',
    describe: () => 'Private',
  },
  {
    term: 'RBI',
    kind: 'standard',
    describe: () => 'The Reserve Bank of India',
  },
  {
    term: 'Registration Act',
    kind: 'standard',
    describe: () => 'Registration Act, 1908',
  },
  {
    term: 'Revenue from operations',
    kind: 'standard',
    describe: () => 'Revenue from operations represents the total turnover of the business from the operating activities (Net of Returns) as well as it provides information regarding the year-over-year growth of our Company',
  },
  {
    term: 'ROE',
    kind: 'standard',
    describe: () => 'Return on Equity',
  },
  {
    term: 'RONW',
    kind: 'standard',
    describe: () => 'Return on Net Worth',
  },
  {
    term: 'Rs./ Rupees/ INR/',
    kind: 'standard',
    describe: () => 'Indian Rupees',
  },
  {
    term: 'RTGS',
    kind: 'standard',
    describe: () => 'Real Time Gross Settlement',
  },
  {
    term: 'SCRR',
    kind: 'standard',
    describe: () => 'Securities Contracts (Regulation) Rules, 1957, as amended from time to time',
  },
  {
    term: 'SCSB',
    kind: 'standard',
    describe: () => 'Self-Certified Syndicate Banks',
  },
  {
    term: 'SEBI (SAST) Regulations Sec.',
    kind: 'standard',
    describe: () => 'and Takeover) Regulations, 2011, as amended from time to time. Section',
  },
  {
    term: 'SEBI Act/ SEBI',
    kind: 'standard',
    describe: () => 'Securities and Exchange Board of India Act, 1992, as amended from time to time',
  },
  {
    term: 'SEBI AIF Regulations',
    kind: 'standard',
    describe: () => 'Securities and Exchange Board of India (Alternative Investment Funds) Regulations, 2012, as amended',
  },
  {
    term: 'SEBI FPI Regulations',
    kind: 'standard',
    describe: () => 'Securities and Exchange Board of India (Foreign Portfolio Investors) Regulations, 2019, as amended from time to time',
  },
  {
    term: 'SEBI FVCI Regulations',
    kind: 'standard',
    describe: () => 'Securities and Exchange Board of India (Foreign Venture Capital Investor) Regulations, 2000, as amended from time to time',
  },
  {
    term: 'SEBI ICDR Master',
    kind: 'standard',
    describe: () => 'SEBI master circular bearing reference number HO/49/14/14(2)2026-',
  },
  {
    term: 'SEBI ICDR Regulation',
    kind: 'standard',
    describe: () => 'Securities and Exchange Board of India (Issue of Capital and Disclosure Requirements) Regulations, 2018, as amended from time to time',
  },
  {
    term: 'SEBI LODR Regulations',
    kind: 'standard',
    describe: () => 'The Securities and Exchange Board of India (Listing Obligation and Disclosure Requirements) Regulations, 2015, as amended, including instructions and clarifications issued by SEBI from time to time',
  },
  {
    term: 'SEBI PIT Regulations',
    kind: 'standard',
    describe: () => 'The Securities and Exchange Board of India (Prohibition of Insider Trading) Regulations, 2015, as amended from time to time including instructions and clarifications issued by SEBI from time to time',
  },
  {
    term: 'SEBI RTA Master Circular',
    kind: 'standard',
    describe: () => 'SEBI master circular no. SEBI/HO/38/13/(4)2026-MIRSD-POD/I/4298/2026 dated February 6, 2026',
  },
  {
    term: 'SIDBI',
    kind: 'standard',
    describe: () => 'Small Industries Development Bank of India',
  },
  {
    term: 'SME',
    kind: 'standard',
    describe: () => 'Small and Medium Enterprises',
  },
  {
    term: 'STT',
    kind: 'standard',
    describe: () => 'Securities Transaction Tax',
  },
  {
    term: 'TAN',
    kind: 'standard',
    describe: () => 'Tax Deduction Account Number',
  },
  {
    term: 'TDS',
    kind: 'standard',
    describe: () => 'Tax Deducted at Source',
  },
  {
    term: 'Trade Marks Act',
    kind: 'standard',
    describe: () => 'Trade Marks Act, 1999',
  },
  {
    term: 'U.S. GAAP',
    kind: 'standard',
    describe: () => 'Generally Accepted Accounting Principles in the United States of America',
  },
  {
    term: 'U.S. Securities Act',
    kind: 'standard',
    describe: () => 'United States Securities Act of 1933',
  },
  {
    term: 'VCF/ Venture Capital Fund',
    kind: 'standard',
    describe: () => 'Venture capital funds as defined in and registered with SEBI under the SEBI VCF Regulations and the SEBI AIF Regulations',
  },
  {
    term: 'w.e.f.',
    kind: 'standard',
    describe: () => 'With effect from',
  },
  {
    term: 'WACA',
    kind: 'standard',
    describe: () => 'Weighted average cost of acquisition',
  },
];
